'https://plantuml.com/mindmap-diagram
@startmindmap

title veux - AOSP partitions layout

* boot
** header v3
** data
***[#lightblue] kernel
*** ramdisk
**** init

* vendor_boot
** header v3
***[#lightblue] cmdline
** data
***[#lightblue] dtb
*** ramdisk
****[#orange] recovery
**** fstab

* dtbo
** <empty>

legend right
|<#orange> Recovery|
|<#lightblue> Kernel resources|
endlegend

@endmindmap
