'https://plantuml.com/mindmap-diagram
@startmindmap

title veux - MIUI/HyperOS partitions layout

* boot
** header v3
** data
***[#lightblue] kernel
*** ramdisk
**** init
****[#orange] recovery

* vendor_boot
** header v3
***[#lightblue] cmdline
** data
***[#lightblue] dtb
*** ramdisk
****[#lightblue] modules
**** fstab

* dtbo
**[#lightblue] dtb overlay

legend right
|<#orange> Recovery|
|<#lightblue> Kernel resources|
endlegend

@endmindmap
